import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {Miniflare} from 'miniflare';
import worker,{calculate,digest} from '../worker.js';
test('D1: account, raid, waitlist, permission, attendance, payout, concurrency',async()=>{
 const mf=new Miniflare({modules:true,scriptPath:'worker.js',compatibilityDate:'2026-08-01',d1Databases:['DB'],bindings:{FRONTEND_URL:'https://z860415.github.io/Maple/',PUBLIC_API_URL:'https://maple-api.z860415.workers.dev',DISCORD_CLIENT_ID:'123',DISCORD_CLIENT_SECRET:'test-only'}});
 try{const db=await mf.getD1Database('DB');const schema=await readFile('schema.sql','utf8');
 // D1 exec takes one statement per line; preserve multiline trigger as a single line.
 await db.exec(schema.replace(/CREATE TRIGGER[\s\S]*?END;/,m=>m.replace(/\n/g,' ')));
 const p={name:'小楓',job:'聖騎士',level:177,attack:37000,boss:30,ignore:17};
 for(const uid of ['1','2','3','4']){await db.prepare('INSERT INTO users(id,name,profile) VALUES(?,?,?)').bind(uid,'DC '+uid,JSON.stringify(p)).run();await db.prepare('INSERT INTO sessions VALUES(?,?,?)').bind(await digest('token'+uid),uid,Date.now()+1000000).run()}
 async function api(path,method='GET',data,uid='1',expected=200){const res=await mf.dispatchFetch('https://api.test/api'+path,{method,headers:{Authorization:'Bearer token'+uid,Origin:'https://z860415.github.io',...(data?{'Content-Type':'application/json'}:{})},body:data?JSON.stringify(data):undefined});const out=await res.json();assert.equal(res.status,expected,JSON.stringify(out));assert.equal(res.headers.get('Access-Control-Allow-Origin'),'https://z860415.github.io');return out}
 assert.equal((await api('/config')).login_ready,true);await api('/me/profile','PUT',p);await api('/me','GET',null,'bad',401);
 const input={title:'測試王團',bosses:['炎魔'],starts:new Date(Date.now()+3600000).toISOString(),capacity:2};
 const alt=await api('/me/characters','POST',{...p,name:'小楓分身',job:'主教',dojo:'1.50e'});
 assert.equal(alt.profile.dojo,'1.5E');
 for(const dojo of ['-1E','1e8','abc','Infinity',1.5])await api('/me/characters/'+encodeURIComponent(alt.id),'PUT',{...p,dojo},'1',400);
 assert.equal((await api('/me')).characters.length,2);
 await api('/me/characters/'+encodeURIComponent(alt.id),'PUT',{...p,name:'盜用'},'2',404);
 await api('/raids','POST',{...input,character_id:alt.id},'2',400);
 const altRaid=await api('/raids','POST',{...input,character_id:alt.id});
 assert.equal((await api('/raids')).find(r=>r.id===altRaid.id).members[0].profile.name,'小楓分身');
 await api('/me/characters/'+encodeURIComponent(alt.id),'PUT',{...p,name:'分身新名稱',dojo:'0.23'});
 assert.equal((await api('/me')).characters.find(c=>c.id===alt.id).profile.dojo,'0.23E');
 assert.equal((await api('/me/history'))[0].profile.name,'小楓分身');
 assert.equal((await api('/me/history'))[0].profile.dojo,'1.5E');
 await api('/me/history','GET',null,'2').then(rows=>assert.equal(rows.length,0));
 const others=await api('/raids','POST',input,'2');
 await api(`/raids/${others.id}/join`,'POST',{character_id:alt.id});
 assert.equal((await api('/raids')).find(r=>r.id===others.id).members.find(m=>m.user_id==='1').profile.name,'分身新名稱');
 assert.equal((await api('/raids')).find(r=>r.id===others.id).members.find(m=>m.user_id==='1').profile.dojo,'0.23E');
 const {id}=await api('/raids','POST',input);assert.equal((await api('/raids'))[0].members.length,1);
 assert.equal((await api(`/raids/${id}/join`,'POST',{},'2')).seat,'waiting');assert.equal((await api(`/raids/${id}/join`,'POST',{},'3')).seat,'waiting');await api(`/raids/${id}/join`,'POST',{},'3',409);
 await api(`/raids/${id}/roster`,'PUT',{users:['1','2']},'2',403);
 await api(`/raids/${id}/roster`,'PUT',{users:['1','2','3']},'1',400);
 await api(`/raids/${id}/roster`,'PUT',{users:['3']},'1',400);
 await api(`/raids/${id}/roster`,'PUT',{users:['1','4']},'1',400);
 await api(`/raids/${id}/roster`,'PUT',{users:['1','1']},'1',400);
 await api(`/raids/${id}`,'PUT',{...input,capacity:3});
 assert.equal((await api('/raids')).find(r=>r.id===id).members.filter(m=>m.seat==='confirmed').length,1);
 await api(`/raids/${id}/roster`,'PUT',{users:['1','2','3']});
 await api(`/raids/${id}/roster`,'PUT',{users:['1','2']});
 assert.equal((await api('/raids')).find(r=>r.id===id).members.find(m=>m.user_id==='3').seat,'waiting');
 await api(`/raids/${id}/status`,'PUT',{status:'running'},'2',403);
 await api(`/raids/${id}/join`,'DELETE',null,'2');let r=(await api('/raids'))[0];assert.equal(r.members.find(m=>m.user_id==='3').seat,'waiting');
 await api(`/raids/${id}/roster`,'PUT',{users:['1','3']});
 await api(`/raids/${id}/status`,'PUT',{status:'running'});await api(`/raids/${id}/join`,'POST',{},'2',409);
 await api(`/raids/${id}/roster`,'PUT',{users:['1']},'1',409);
 await api(`/raids/${id}/attendance`,'PUT',{users:['1','2']},'1',400);await api(`/raids/${id}/attendance`,'PUT',{users:['1','3']});await api(`/raids/${id}/status`,'PUT',{status:'done'});
 const loot={fee:3,rate:9000,items:[{name:'卷軸',quantity:1,price:10000000}],costs:[{name:'剪刀',quantity:2,points:900,mesos:1000000,basis:'points'}]};
 const saved=await api(`/raids/${id}/settlement`,'POST',loot);assert.equal(saved.result.each,4350000);
 await api(`/raids/${id}/attendance`,'PUT',{users:['1']},'1',409);await api(`/raids/${id}/paid/3`,'PUT',{paid:true});await api(`/raids/${id}/settlement`,'DELETE',null,'1',409);await api(`/raids/${id}/paid/3`,'PUT',{paid:false});await api(`/raids/${id}/settlement`,'DELETE');
 const race=await api('/raids','POST',input);
 const source=await api('/raids','POST',input),splitPath=`/raids/${source.id}/split`;
 await api(`/raids/${source.id}/join`,'POST',{character_id:alt.id,note:'分隊備註',available:'晚上'},'1',409);
 await api(`/raids/${source.id}/join`,'POST',{note:'分隊備註',available:'晚上'},'2');
 await api(`/raids/${source.id}/join`,'POST',{},'3');
 const splitPayload={...input,title:'二隊',users:['2','3'],owner:'2'};
 await api(`/raids/${source.id}/payout-owner`,'PUT',{user_id:'2'});
 await api(`/raids/${source.id}`,'PUT',input);
 assert.equal((await api('/raids')).find(r=>r.id===source.id).payout_owner,'2');
 await api(splitPath,'POST',splitPayload,'2',403);
 await api(splitPath,'POST',{...splitPayload,users:[]},'1',400);
 await api(splitPath,'POST',{...splitPayload,users:['2','2']},'1',400);
 await api(splitPath,'POST',{...splitPayload,users:['1','2']},'1',400);
 await api(splitPath,'POST',{...splitPayload,owner:'4'},'1',400);
 await api(splitPath,'POST',{...splitPayload,capacity:1},'1',400);
 const sourceBefore=(await api('/raids')).find(r=>r.id===source.id);
 const splitResults=await Promise.all([1,2].map(()=>mf.dispatchFetch('https://api.test/api'+splitPath,{method:'POST',headers:{Authorization:'Bearer token1','Content-Type':'application/json'},body:JSON.stringify(splitPayload)})));
 assert.equal(splitResults.filter(res=>res.status===200).length,1);
 assert(splitResults.every(res=>[200,400,409].includes(res.status)));
 const newSplit=await splitResults.find(res=>res.status===200).json();
 const splitRaids=await api('/raids'),destination=splitRaids.find(r=>r.id===newSplit.id);
 assert.equal(destination.owner,'2');assert.equal(destination.starts,input.starts);
 assert.deepEqual(destination.members.map(m=>m.user_id).sort(),['2','3']);
 assert(destination.members.every(m=>m.seat==='confirmed'&&!m.attended&&!m.paid));
 assert.deepEqual(destination.members.find(m=>m.user_id==='2').profile,sourceBefore.members.find(m=>m.user_id==='2').profile);
 assert.equal(destination.members.find(m=>m.user_id==='2').note,'分隊備註');assert.equal(destination.members.find(m=>m.user_id==='2').available,'晚上');
 assert.deepEqual(splitRaids.find(r=>r.id===source.id).members.map(m=>m.user_id),['1']);
 assert.equal(splitRaids.find(r=>r.id===source.id).payout_owner,undefined);
 await api(`/raids/${newSplit.id}/roster`,'PUT',{users:['2','3']},'2');
 await api(`/raids/${source.id}/status`,'PUT',{status:'running'});
 await api(splitPath,'POST',splitPayload,'1',409);
 const transfer=await api('/raids','POST',input),transferPath=`/raids/${transfer.id}`;
 await api(transferPath+'/join','POST',{},'2');await api(transferPath+'/join','POST',{},'3');
 await api(transferPath+'/owner','PUT',{user_id:'2'},'2',403);
 await api(transferPath+'/owner','PUT',{user_id:'1'},'1',400);
 await api(transferPath+'/owner','PUT',{user_id:'4'},'1',400);
 await api(transferPath+'/roster','PUT',{users:['1','2']});
 await api(transferPath+'/owner','PUT',{user_id:'3'});
 let transferred=(await api('/raids')).find(r=>r.id===transfer.id);
 assert.equal(transferred.owner,'3');assert.equal(transferred.members.find(m=>m.user_id==='1').seat,'waiting');
 assert.equal(transferred.members.find(m=>m.user_id==='1').note,'');
 assert.equal(transferred.members.filter(m=>m.seat==='confirmed').length,2);
 await api(transferPath+'/roster','PUT',{users:['1','2']},'1',403);
 await api(transferPath+'/owner','PUT',{user_id:'2'},'3');
 await api(transferPath+'/status','PUT',{status:'running'},'2');
 await api(transferPath+'/owner','PUT',{user_id:'1'},'2',409);
 await api(transferPath+'/attendance','PUT',{users:['2','3']},'2');
 await api(transferPath+'/status','PUT',{status:'done'},'2');
 const transferSettlement=await api(transferPath+'/settlement','POST',loot,'2');
 await api(transferPath+'/paid/3','PUT',{paid:true},'2');
 await api(transferPath+'/owner','PUT',{user_id:'3'},'2');
 transferred=(await api('/raids')).find(r=>r.id===transfer.id);
 assert.deepEqual(transferred.settlement,transferSettlement);assert.equal(transferred.members.find(m=>m.user_id==='3').paid,1);
 await api(transferPath+'/paid/3','PUT',{paid:false},'2',403);
 await api(transferPath+'/paid/3','PUT',{paid:false},'3');
 await api(transferPath+'/payout-owner','PUT',{user_id:'4'},'3',400);
 await api(transferPath+'/payout-owner','PUT',{user_id:'1'},'2',403);
 await api(transferPath+'/payout-owner','PUT',{user_id:'1'},'3');
 await api(transferPath+'/paid/3','PUT',{paid:true},'1');
 await api(transferPath+'/paid/3','PUT',{paid:false},'1');
 await api(transferPath+'/attendance','PUT',{users:['2']},'1',403);
 await api(transferPath+'/owner','PUT',{user_id:'2'},'1',403);
 await api(transferPath+'/payout-owner','PUT',{user_id:'2'},'1',403);
 await api(transferPath+'/settlement','DELETE',null,'1');
 await api(transferPath+'/settlement','POST',loot,'1');
 await api(transferPath+'/payout-owner','PUT',{user_id:'3'},'3');
 await api(transferPath+'/paid/3','PUT',{paid:true},'1',403);
 const cancelled=await api('/raids','POST',input);
 await api(`/raids/${cancelled.id}/join`,'POST',{},'2');
 await api(`/raids/${cancelled.id}/payout-owner`,'PUT',{user_id:'2'});
 await api(`/raids/${cancelled.id}/join`,'DELETE',null,'2');
 assert.equal((await api('/raids')).find(r=>r.id===cancelled.id).payout_owner,undefined);
 await api(`/raids/${cancelled.id}/join`,'POST',{},'2');await api(`/raids/${cancelled.id}/status`,'PUT',{status:'cancelled'});
 await api(`/raids/${cancelled.id}/owner`,'PUT',{user_id:'2'},'1',409);
 const outcomes=await Promise.all(['2','3','4'].map(uid=>mf.dispatchFetch(`https://api.test/api/raids/${race.id}/join`,{method:'POST',headers:{Authorization:'Bearer token'+uid,'Content-Type':'application/json'},body:'{}'})));
 assert(outcomes.every(r=>[200,409].includes(r.status)));r=(await api('/raids')).find(r=>r.id===race.id);assert.equal(r.members.filter(m=>m.seat==='confirmed').length,1);
 const challenge=await digest('a'.repeat(64));const login=await mf.dispatchFetch('https://api.test/api/auth/login?challenge='+challenge,{redirect:'manual'});assert.equal(new URL(login.headers.get('Location')).searchParams.get('scope'),'identify');assert(login.headers.get('Set-Cookie').includes('HttpOnly'));
 await db.prepare('INSERT INTO tickets VALUES(?,?,?,?)').bind(await digest('b'.repeat(64)),'1',Date.now()+60000,challenge).run();
 await api('/auth/exchange','POST',{ticket:'b'.repeat(64),verifier:'wrong'.repeat(10)},'1',401);const ex=await api('/auth/exchange','POST',{ticket:'b'.repeat(64),verifier:'a'.repeat(64)});assert(ex.token);await api('/auth/exchange','POST',{ticket:'b'.repeat(64),verifier:'a'.repeat(64)},'1',401);
 const calls=[];const env={DB:db,FRONTEND_URL:'https://z860415.github.io/Maple/',PUBLIC_API_URL:'https://api.test',DISCORD_CLIENT_ID:'123',DISCORD_CLIENT_SECRET:'test',DISCORD_WEBHOOK_URL:'https://discord.com/api/webhooks/123/test',TEST_FETCH:async(url,opts)=>{calls.push({url,opts});return Response.json(url.endsWith('/token')?{access_token:'mock'}:url.endsWith('/@me')?{id:'999',username:'外部玩家'}:{id:'555'})}};
 const oauthState=new URL(login.headers.get('Location')).searchParams.get('state');
 const callback=await worker.fetch(new Request('https://api.test/api/auth/callback?state='+oauthState+'&code=test',{headers:{Cookie:'oauth_state='+oauthState}}),env,{waitUntil(){}});
 assert.equal(callback.status,303);assert.equal(calls.length,2);assert(calls[1].url.endsWith('/users/@me'));assert((await db.prepare('SELECT name FROM users WHERE id=?').bind('999').first()).name==='外部玩家');
 for(const origin of ['http://localhost:8000','http://127.0.0.1:8000']){
  const preflight=await mf.dispatchFetch('https://api.test/api/me',{method:'OPTIONS',headers:{Origin:origin}});
  assert.equal(preflight.headers.get('Access-Control-Allow-Origin'),origin);
 }
 const rejected=await mf.dispatchFetch('https://api.test/api/config',{headers:{Origin:'https://untrusted.test'}});
 assert.equal(rejected.headers.get('Access-Control-Allow-Origin'),null);
 const badReturn=await mf.dispatchFetch('https://api.test/api/auth/login?challenge='+challenge+'&return_to='+encodeURIComponent('https://untrusted.test/'));
 assert.equal(badReturn.status,400);
 const localLogin=await mf.dispatchFetch('https://api.test/api/auth/login?challenge='+challenge+'&return_to='+encodeURIComponent('http://localhost:8000/'),{redirect:'manual'});
 assert.equal(localLogin.status,303);
 const localState=new URL(localLogin.headers.get('Location')).searchParams.get('state');
 const localCallback=await worker.fetch(new Request('https://api.test/api/auth/callback?state='+localState+'&code=test',{headers:{Cookie:'oauth_state='+localState}}),env,{waitUntil(){}});
 assert.equal(localCallback.status,303);assert(localCallback.headers.get('Location').startsWith('http://localhost:8000/#ticket='));
 const localTicket=new URL(localCallback.headers.get('Location')).hash.slice(8);
 const localExchange=await api('/auth/exchange','POST',{ticket:localTicket,verifier:'a'.repeat(64)});assert(localExchange.token);
 assert.equal((await db.prepare('SELECT expires FROM sessions WHERE hash=?').bind(await digest(localExchange.token)).first()).expires,0);
 const persistentHeaders={Authorization:'Bearer '+localExchange.token};
 assert.equal((await mf.dispatchFetch('https://api.test/api/me',{headers:persistentHeaders})).status,200);
 await mf.dispatchFetch('https://api.test/api/auth/logout',{method:'POST',headers:persistentHeaders});
 assert.equal((await mf.dispatchFetch('https://api.test/api/me',{headers:persistentHeaders})).status,401);
 const sync=await worker.fetch(new Request(`https://api.test/api/raids/${id}/discord`,{method:'POST',headers:{Authorization:'Bearer token1'}}),env,{waitUntil(){}});assert.equal(sync.status,200);assert.equal(calls.at(-1).opts.method,'POST');
 await worker.fetch(new Request(`https://api.test/api/raids/${id}/discord`,{method:'POST',headers:{Authorization:'Bearer token1'}}),env,{waitUntil(){}});assert.equal(calls.at(-1).opts.method,'PATCH');assert.deepEqual(JSON.parse(calls.at(-1).opts.body).allowed_mentions,{parse:[]});
 await api('/auth/logout','POST');await api('/me','GET',null,'1',401);
 }finally{await mf.dispose()}
});
test('exact fractional fee and cost rounding; safe total bounds',()=>{
 const p={fee:0.1,rate:3,items:[{name:'a',quantity:1,price:10000001}],costs:[{name:'b',quantity:99,points:1,mesos:0,basis:'points'}]};
 const r=calculate(p,['1','2']);assert.equal(r.total,6656667);assert.equal(r.each,3328333);assert.equal(r.remainder,1);
 assert.throws(()=>calculate({...p,items:[{name:'a',quantity:100000,price:1e12}]},['1']));
});
