import {JSDOM} from 'jsdom';
import {readFileSync} from 'node:fs';
import {join,resolve} from 'node:path';
import assert from 'node:assert/strict';
import {Miniflare} from 'miniflare';
import {digest} from '../worker.js';
const root=resolve('.'),url='https://api.test';let dom;const stderr='';
const pause=()=>new Promise(r=>setTimeout(r,25));
async function until(test,label){for(let i=0;i<200;i++){if(await test())return;await pause()}throw Error('Timed out: '+label+' '+dom?.window.document.querySelector('#notice').textContent)}
const mf=new Miniflare({modules:true,scriptPath:'worker.js',compatibilityDate:'2026-08-01',d1Databases:['DB'],bindings:{FRONTEND_URL:'https://z860415.github.io/Maple/'}});
try{
const db=await mf.getD1Database('DB');await db.exec(readFileSync('schema.sql','utf8').replace(/CREATE TRIGGER[\s\S]*?END;/,m=>m.replace(/\n/g,' ')));
await db.prepare("INSERT INTO users(id,name) VALUES('1','測試玩家')").run();await db.prepare('INSERT INTO sessions VALUES(?,?,?)').bind(await digest('ui-token'),'1',Date.now()+1000000).run();
 const html=readFileSync(join(root,'web/index.html'),'utf8').replace(/<script[\s\S]*?<\/script>/g,'');
 dom=new JSDOM(html,{url,runScripts:'outside-only'});
 const w=dom.window, d=w.document;
 w.fetch=(p,opt)=>mf.dispatchFetch(new URL(p,url),opt);
 w.sessionStorage.setItem('guild_token','ui-token');
 w.confirm=()=>true;
 w.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','')};
 w.HTMLDialogElement.prototype.close=function(){this.removeAttribute('open')};
 w.eval(readFileSync(join(root,'web/config.js'),'utf8'));
 w.eval(readFileSync(join(root,'web/app.js'),'utf8'));
 const click=s=>{assert.ok(d.querySelector(s),'Missing '+s);d.querySelector(s).click()};
 const fill=(s,v)=>{const e=d.querySelector(s);assert.ok(e,s);e.value=String(v);e.dispatchEvent(new w.Event('input',{bubbles:true}))};
 const submit=s=>d.querySelector(s).dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
 const closed=()=>!d.querySelector('#modal').hasAttribute('open');

 await until(()=>!d.querySelector('#workspace').hidden,'signed in');click('#profileButton');
 for(const [name,value] of Object.entries({name:'介面測試員',job:'聖騎士',level:177,attack:37000,boss:30,ignore:17}))fill(`[name="${name}"]`,value);
 submit('#profileForm');await until(closed,'profile saved');
 click('#profileButton');click('#addCharacter');
 for(const [name,value] of Object.entries({name:'分身主教',job:'主教',level:180,attack:40000,boss:35,ignore:20}))fill(`[name="${name}"]`,value);
 submit('#profileForm');await until(closed,'second character saved');
 click('#newRaid');fill('[name=title]','週六測試王團');fill('[name=bosses]','皮卡啾');fill('[name=starts]','2099-09-30T22:00');submit('#raidForm');
 await until(()=>d.querySelector('#start'),'created raid');
 assert.match(d.querySelector('#detail').textContent,/介面測試員/);
 assert.equal(d.querySelector('.calendar-toolbar h2').textContent,'2099 年 9 月');
 assert.equal(d.querySelectorAll('.calendar-day').length,42);
 assert.match(d.querySelector('#dayHeading').textContent,/星期三/);
 assert.ok(d.querySelector('[data-date="2099-09-30"]').closest('.calendar-day').querySelector('.calendar-event'));
 d.querySelector('.calendar-event').dispatchEvent(new w.Event('mouseenter'));
 assert.equal(d.querySelector('#raidTooltip').hidden,false);
 assert.match(d.querySelector('#raidTooltip').textContent,/週六測試王團/);
 assert.match(d.querySelector('#raidTooltip').textContent,/皮卡啾/);
 assert.match(d.querySelector('#raidTooltip').textContent,/1 \/ 6/);
 d.querySelector('.calendar-event').dispatchEvent(new w.Event('mouseleave'));
 assert.equal(d.querySelector('#raidTooltip').hidden,true);
 click('.calendar-event');assert.equal(d.activeElement.id,'detail');
 click('#nextMonth');assert.equal(d.querySelector('.calendar-toolbar h2').textContent,'2099 年 10 月');
 click('#prevMonth');click('[data-date="2099-09-30"]');
 const originalId=Number(d.querySelector('.raid-card.selected').dataset.raid);
 await db.prepare("INSERT INTO users(id,name,profile) VALUES('2','其他團長',?)").bind(JSON.stringify({name:'其他角色',job:'主教',level:180,attack:40000,boss:35,ignore:20})).run();
 await db.prepare('UPDATE raids SET owner=? WHERE id=?').bind('2',originalId).run();
 click('#refresh');await until(()=>!d.querySelector('#edit'),'other leader loaded');
 click('#duplicate');assert.equal(d.querySelector('[name=title]').value,'週六測試王團');
 fill('[name=title]','分身複製團');fill('[name=character_id]',d.querySelector('[name=character_id]').options[1].value);
 submit('#raidForm');await until(()=>d.querySelector('#detail h2')?.textContent==='分身複製團','copy created');
 assert.match(d.querySelector('#detail').textContent,/分身主教/);
 assert.equal((await db.prepare('SELECT owner FROM raids WHERE id=?').bind(originalId).first()).owner,'2');
 click('#historyButton');await until(()=>d.querySelector('#modalTitle').textContent==='參團紀錄','history');
 assert.match(d.querySelector('#modalBody').textContent,/介面測試員/);assert.match(d.querySelector('#modalBody').textContent,/分身主教/);click('#closeModal');
 click('#start');await until(()=>d.querySelector('.attend'),'started');
 d.querySelector('.attend').checked=true;click('#saveAttendance');
 await until(()=>d.querySelector('#notice').textContent==='出席名單已儲存','attendance saved');
 click('#done');await until(()=>d.querySelector('#loot'),'completed');click('#loot');
 fill('#items td:nth-child(1) input','混沌卷軸');fill('#items td:nth-child(3) input',10000000);
 click('#addCost');fill('#costs td:nth-child(1) input','天氣');fill('#costs td:nth-child(2) input',2);fill('#costs td:nth-child(3) input',900);
 assert.equal(d.querySelector('#costs td:nth-child(4) input').value,'1000000');
 assert.equal(d.querySelector('#preview').textContent,'8,700,000 楓幣');
 submit('#lootForm');await until(()=>d.querySelector('.paid'),'settled');
 assert.match(d.querySelector('.summary').textContent,/8,700,000/);
 click('.paid');await until(()=>d.querySelector('.paid')?.dataset.paid==='1','marked paid');
 click('#resetLoot');await until(()=>d.querySelector('#notice').textContent.includes('取消已領'),'paid reset prevented');
 click('#logout');await until(()=>!d.querySelector('#welcome').hidden,'logged out');
 console.log('PASS: UI sign-in, profile, create, attendance, settlement, linked cost conversion, payment lock, logout');
}finally{dom?.window.close();await mf.dispose()}
