import {JSDOM} from 'jsdom';
import {readFileSync} from 'node:fs';
import {join,resolve} from 'node:path';
import assert from 'node:assert/strict';
import {Miniflare} from 'miniflare';
import {digest} from '../worker.js';
const root=resolve('.'),url='https://api.test';let dom;const stderr='';
const pause=()=>new Promise(r=>setTimeout(r,25));
async function until(test,label){for(let i=0;i<200;i++){if(await test())return;await pause()}throw Error('Timed out: '+label+' '+dom?.window.document.querySelector('#notice').textContent)}
const mf=new Miniflare({modules:true,scriptPath:'worker.js',compatibilityDate:'2026-08-01',d1Databases:['DB'],bindings:{FRONTEND_URL:'https://z860415.github.io/Maple/',DISCORD_BOT_TOKEN:'mock-bot',DISCORD_NOTIFICATION_CHANNEL_ID:'555'}});
try{
const db=await mf.getD1Database('DB');await db.exec(readFileSync('schema.sql','utf8').replace(/CREATE TRIGGER[\s\S]*?END;/,m=>m.replace(/\n/g,' ')));
await db.prepare("INSERT INTO users(id,name) VALUES('1','測試玩家')").run();await db.prepare('INSERT INTO sessions VALUES(?,?,?)').bind(await digest('ui-token'),'1',Date.now()+1000000).run();
 const html=readFileSync(join(root,'web/index.html'),'utf8').replace(/<script[\s\S]*?<\/script>/g,'');
 dom=new JSDOM(html,{url,runScripts:'outside-only'});
 const w=dom.window, d=w.document;
 w.fetch=(p,opt)=>mf.dispatchFetch(new URL(p,url),opt);
 w.sessionStorage.setItem('guild_token','ui-token');
 w.confirm=()=>true;
 w.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','')};
 w.HTMLDialogElement.prototype.close=function(){this.removeAttribute('open')};
 w.eval(readFileSync(join(root,'web/config.js'),'utf8'));
 w.eval(readFileSync(join(root,'web/app.js'),'utf8')+'\nwindow.testState=state;window.testRenderList=renderList;window.testRememberLogin=rememberLogin;');
 const click=s=>{assert.ok(d.querySelector(s),'Missing '+s);d.querySelector(s).click()};
 const fill=(s,v)=>{const e=d.querySelector(s);assert.ok(e,s);e.value=String(v);e.dispatchEvent(new w.Event('input',{bubbles:true}))};
 const submit=s=>d.querySelector(s).dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
 const closed=()=>!d.querySelector('#modal').hasAttribute('open');

 await until(()=>!d.querySelector('#workspace').hidden,'signed in');click('#profileButton');
 assert.match(d.cookie,/guild_token=ui-token/);assert.equal(w.sessionStorage.getItem('guild_token'),null);
 const anotherTab=new JSDOM(html,{url,runScripts:'outside-only',cookieJar:dom.cookieJar});
 anotherTab.window.fetch=w.fetch;anotherTab.window.eval(readFileSync(join(root,'web/app.js'),'utf8'));
 await until(()=>!anotherTab.window.document.querySelector('#workspace').hidden,'remembered in new tab');
 anotherTab.window.document.cookie='guild_token=; Path=/; Max-Age=0';
 anotherTab.window.dispatchEvent(new anotherTab.window.Event('focus'));
 await until(()=>!anotherTab.window.document.querySelector('#welcome').hidden,'cleared cookie logged out');
 w.testRememberLogin('ui-token');
 anotherTab.window.close();
 for(const [name,value] of Object.entries({name:'介面測試員',job:'聖騎士',level:177,attack:37000,boss:30,ignore:17}))fill(`[name="${name}"]`,value);
 submit('#profileForm');await until(closed,'profile saved');
 click('#profileButton');click('#addCharacter');
 for(const [name,value] of Object.entries({name:'分身主教',job:'主教',level:180,attack:40000,boss:35,ignore:20}))fill(`[name="${name}"]`,value);
 submit('#profileForm');await until(closed,'second character saved');
 assert.equal(d.querySelector('#toastMessage').textContent,'角色已新增');
 assert.equal(d.querySelector('#toast').hidden,false);
 click('#profileButton');
 const savedCharacters=[...d.querySelector('#manageCharacter').options];
 const secondId=savedCharacters.find(option=>option.textContent.includes('分身主教')).value;
 fill('#manageCharacter',secondId);d.querySelector('#manageCharacter').dispatchEvent(new w.Event('change'));
 click('#editCharacter');
 assert.equal(d.querySelector('[name=name]').value,'分身主教');
 fill('[name=level]',185);fill('[name=attack]',45000);fill('[name=dojo]','0.23e');
 assert.equal(d.querySelector('[name=deathSquad]').checked,false);click('[name=deathSquad]');
 submit('#profileForm');await until(closed,'existing character updated');
 assert.equal(d.querySelector('#toastMessage').textContent,'角色修改已儲存');
 assert.equal(d.querySelector('#toast').hidden,false);
 click('#profileButton');fill('#manageCharacter',secondId);d.querySelector('#manageCharacter').dispatchEvent(new w.Event('change'));
 assert.equal(d.querySelector('[name=level]').value,'185');
 assert.equal(d.querySelector('[name=attack]').value,'45000');
 assert.equal(d.querySelector('[name=dojo]').value,'0.23E');
 assert.equal(d.querySelector('[name=deathSquad]').checked,true);
 assert.equal(d.querySelector('#manageCharacter').options.length,2);
 click('#closeModal');
 click('#newRaid');fill('[name=title]','週六測試王團');fill('[name=bosses]','皮卡啾');fill('[name=starts]','2099-09-30T22:00');submit('#raidForm');
 await until(()=>d.querySelector('#start'),'created raid');
 assert.match(d.querySelector('#detail').textContent,/介面測試員/);
 assert.equal(d.querySelector('#calendar').hidden,true);
 click('[data-filter="open"]');assert.equal(d.querySelector('#calendar').hidden,false);
 assert.equal(d.querySelector('.calendar-toolbar h2').textContent,'2099 年 9 月');
 assert.equal(d.querySelectorAll('.calendar-day').length,42);
 assert.match(d.querySelector('#dayHeading').textContent,/星期三/);
 assert.ok(d.querySelector('[data-date="2099-09-30"]').closest('.calendar-day').querySelector('.calendar-event'));
 d.querySelector('.calendar-event').dispatchEvent(new w.Event('mouseenter'));
 assert.equal(d.querySelector('#raidTooltip').hidden,false);
 assert.match(d.querySelector('#raidTooltip').textContent,/週六測試王團/);
 assert.match(d.querySelector('#raidTooltip').textContent,/皮卡啾/);
 assert.match(d.querySelector('#raidTooltip').textContent,/1 \/ 6/);
 d.querySelector('.calendar-event').dispatchEvent(new w.Event('mouseleave'));
 assert.equal(d.querySelector('#raidTooltip').hidden,true);
 click('.calendar-event');assert.equal(d.activeElement.id,'detail');
 click('#nextMonth');assert.equal(d.querySelector('.calendar-toolbar h2').textContent,'2099 年 10 月');
 click('#prevMonth');click('[data-date="2099-09-30"]');
 const originalId=Number(d.querySelector('.raid-card.selected').dataset.raid);
 await db.prepare("INSERT INTO users(id,name,profile) VALUES('2','其他團長',?)").bind(JSON.stringify({name:'其他角色',job:'主教',level:180,attack:40000,boss:35,ignore:20})).run();
 await db.prepare('UPDATE raids SET owner=? WHERE id=?').bind('2',originalId).run();
 click('#refresh');await until(()=>!d.querySelector('#edit'),'other leader loaded');
 click('#duplicate');assert.equal(d.querySelector('[name=title]').value,'週六測試王團');
 fill('[name=title]','分身複製團');fill('[name=character_id]',d.querySelector('[name=character_id]').options[1].value);
 submit('#raidForm');await until(()=>d.querySelector('#detail h2')?.textContent==='分身複製團','copy created');
 assert.match(d.querySelector('#detail').textContent,/分身主教/);
 assert.equal(d.querySelector('#calendar').hidden,true);
 assert.equal(d.querySelectorAll('#raidList .raid-card').length,2);
 click('[data-filter="mine"]');assert.equal(d.querySelector('#calendar').hidden,true);
 assert.equal(d.querySelectorAll('#raidList .raid-card').length,2);
 const realRaids=w.testState.raids.slice();
 w.testState.raids.push(...['cancelled','done','running'].map((status,i)=>({...realRaids[0],id:900+i,status,starts:'2099-12-01T14:00:00Z'})));w.testRenderList();
 assert.deepEqual([...d.querySelectorAll('#raidList .badge')].map(e=>e.textContent),['開打中','招募中','招募中','已完成','已取消']);
 fill('#mineStatus','done');d.querySelector('#mineStatus').dispatchEvent(new w.Event('change'));
 assert.equal(d.querySelectorAll('#raidList .raid-card').length,1);
 assert.equal(d.querySelector('#raidList .badge').textContent,'已完成');
 fill('#mineStatus','all');d.querySelector('#mineStatus').dispatchEvent(new w.Event('change'));
 w.testState.raids=realRaids;
 click('[data-filter="all"]');assert.equal(d.querySelector('#calendar').hidden,true);
 assert.equal(d.querySelector('#mineFilters').hidden,true);
 assert.equal((await db.prepare('SELECT owner FROM raids WHERE id=?').bind(originalId).first()).owner,'2');
 click('#historyButton');await until(()=>d.querySelector('#modalTitle').textContent==='參團紀錄','history');
 assert.match(d.querySelector('#modalBody').textContent,/介面測試員/);assert.match(d.querySelector('#modalBody').textContent,/分身主教/);click('#closeModal');
 const rosterRaid=w.testState.selected;
 await db.prepare("INSERT INTO users(id,name,profile) VALUES('3','備選玩家','{}')").run();
 for(const user of ['2','3'])await db.prepare("INSERT INTO signups(raid_id,user_id,profile,seat,joined) VALUES(?,?,?,'waiting',?)").bind(rosterRaid,user,JSON.stringify({name:'備選'+user,job:'主教',level:180,attack:40000,boss:0,ignore:0}),Date.now()).run();
 click('#refresh');await until(()=>d.querySelectorAll('.roster').length===3,'waiting roster loaded');
 assert.equal(d.querySelectorAll('.roster:checked').length,1);
 assert.equal(d.querySelector('.roster[data-user="1"]').disabled,true);
 assert.equal(d.querySelector('#saveRoster').parentElement.className,'roster-toolbar');
 assert.equal(d.querySelector('#splitRaid').parentElement,d.querySelector('#edit').parentElement);
 assert.equal(d.querySelector('#edit').nextElementSibling.id,'splitRaid');
 assert.equal(d.querySelector('#start').parentElement.firstElementChild.id,'start');
 assert.equal(d.querySelector('#cancel').parentElement.lastElementChild.id,'cancel');
 assert.equal(d.querySelector('.roster-table th:last-child').textContent,'操作');
 assert.deepEqual([...d.querySelectorAll('.roster-table th')].map(th=>th.textContent),['角色 / 職業','等級','乾表 / B傷 / 無視','武陵','敢死隊象徵','狀態','備註','操作']);
 assert.equal(d.querySelector('.roster-table tbody tr').children.length,8);
 assert.match(d.querySelector('.roster-table tbody tr').children[0].textContent,/分身主教 \/ 主教/);
 assert.equal(d.querySelector('.roster-table tbody tr').children[2].textContent,'45,000 / 35% / 20%');
 assert.equal(d.querySelector('.roster-table tbody tr').children[4].textContent,'有');
 assert.match(d.querySelector('.roster-table tbody').textContent,/0.23E/);
 assert.equal(d.querySelectorAll('.roster-table td small').length,0);
 assert.equal(d.querySelector('.transfer-owner').closest('td'),d.querySelector('.transfer-owner').closest('tr').lastElementChild);
 click('#selectRoster');assert.equal(d.querySelectorAll('.roster:checked').length,3);
 click('#saveRoster');await until(()=>d.querySelector('#toastMessage').textContent==='正選名單已儲存','batch roster saved');
 assert.equal(d.querySelector('#toast').hidden,false);
 assert.equal(d.querySelector('#notice').hidden,true);
 click('#dismissToast');assert.equal(d.querySelector('#toast').hidden,true);
 assert.equal((await db.prepare("SELECT COUNT(*) AS n FROM signups WHERE raid_id=? AND seat='confirmed'").bind(rosterRaid).first()).n,3);
 click('#selectRoster');assert.equal(d.querySelectorAll('.roster:checked').length,1);
 click('#saveRoster');await until(()=>d.querySelector('#toastMessage').textContent==='正選名單已儲存'&&d.querySelectorAll('.roster:checked').length===1&&!d.querySelector('#saveRoster').disabled,'batch roster demoted');
 assert.equal((await db.prepare("SELECT COUNT(*) AS n FROM signups WHERE raid_id=? AND seat='waiting'").bind(rosterRaid).first()).n,2);
 await until(()=>d.querySelector('#toast').hidden,'toast automatically dismissed');
 w.confirm=()=>false;click('.transfer-owner[data-user="2"]');
 assert.ok(d.querySelector('#saveRoster'));w.confirm=()=>true;
 click('.transfer-owner[data-user="2"]');await until(()=>!d.querySelector('#saveRoster'),'ownership transferred in UI');
 assert.equal(d.querySelector('.transfer-owner'),null);
 assert.equal(d.querySelector('#start'),null);
 assert.equal((await db.prepare('SELECT owner FROM raids WHERE id=?').bind(rosterRaid).first()).owner,'2');
 await db.prepare('INSERT INTO sessions VALUES(?,?,0)').bind(await digest('ui-transfer-token'),'2').run();
 const restored=await mf.dispatchFetch(`https://api.test/api/raids/${rosterRaid}/owner`,{method:'PUT',headers:{Authorization:'Bearer ui-transfer-token','Content-Type':'application/json'},body:JSON.stringify({user_id:'1'})});
 assert.equal(restored.status,200);
 click('#refresh');await until(()=>d.querySelector('#saveRoster'),'ownership restored');
 click('#notify-meeting');await until(()=>d.querySelector('#notificationForm'),'notification template loaded');
 assert.equal(d.querySelector('#notifyField'),null);
 assert.match(d.querySelector('#notifyPreview').value,/集合提醒/);
 fill('[name=mode]','scheduled');d.querySelector('[name=mode]').dispatchEvent(new w.Event('change'));fill('[name=minutes]',10);
 assert.match(d.querySelector('#notifyPreview').value,/10 分鐘/);
 fill('#notifyPreview','自訂通知 {團名} {剩餘時間}');
 submit('#notificationForm');await until(closed,'notification schedule saved');
 assert.equal((await db.prepare("SELECT minutes FROM notifications WHERE status='pending'").first()).minutes,10);
 click('#notify-meeting');await until(()=>d.querySelector('[data-cancel-notify]'),'notification schedule loaded');
 assert.equal(d.querySelector('#notifyPreview').value,'自訂通知 分身複製團 10 分鐘');
 click('[data-cancel-notify]');await until(()=>!d.querySelector('[data-cancel-notify]'),'notification schedule cancelled');click('#closeModal');
 click('#start');await until(()=>d.querySelector('.attend'),'started');
 assert.equal(d.querySelector('#saveAttendance'),null);
 click('.attend');await until(()=>d.querySelector('#toastMessage').textContent==='出席狀態已儲存','attendance saved');
 assert.equal((await db.prepare('SELECT attended FROM signups WHERE raid_id=? AND user_id=?').bind(Number(d.querySelector('.raid-card.selected').dataset.raid),'1').first()).attended,1);
 click('#refresh');await until(()=>d.querySelector('#toastMessage').textContent==='已更新最新報名名單','attendance reload');
 assert.equal(d.querySelector('.attend').checked,true);
 click('.attend');await until(()=>d.querySelector('#toastMessage').textContent==='出席狀態已儲存','attendance unchecked saved');
 assert.equal(d.querySelector('.attend').checked,false);
 click('.attend');await until(()=>d.querySelector('#toastMessage').textContent==='出席狀態已儲存','attendance checked again');
 const realFetch=w.fetch;w.fetch=(path,options)=>String(path).endsWith('/attendance')?Promise.reject(Error('測試連線失敗')):realFetch(path,options);
 click('.attend');await until(()=>d.querySelector('#notice').textContent.includes('儲存失敗'),'attendance failure');
 assert.equal(d.querySelector('.attend').checked,true);assert.equal(d.querySelector('.attend').disabled,false);
 w.fetch=realFetch;
 let releaseAttendance;const attendanceGate=new Promise(resolve=>releaseAttendance=resolve);let attendanceRequests=0,attendanceReads=0;
 w.fetch=async(path,options)=>{if(String(path).endsWith('/attendance')){attendanceRequests++;if(attendanceRequests===1)await attendanceGate}else attendanceReads++;return realFetch(path,options)};
 click('.attend');assert.equal(d.querySelector('.attend').checked,false);
 assert.equal(d.querySelector('.attend').disabled,false);assert.equal(d.querySelector('.attendance-status').textContent,'儲存中…');
 click('.attend');assert.equal(d.querySelector('.attend').checked,true);
 assert.equal(d.querySelector('#done').disabled,true);
 releaseAttendance();await until(()=>d.querySelector('.attend').getAttribute('aria-busy')==='false','queued attendance saved');
 assert.equal(attendanceRequests,2);assert.equal(attendanceReads,0);
 assert.equal(d.querySelector('.attend').checked,true);assert.equal(d.querySelector('#done').disabled,false);
 w.fetch=realFetch;
 click('#done');await until(()=>d.querySelector('#loot'),'completed');click('#loot');
 click('[data-preset="混沌卷軸"]');assert.equal(d.querySelector('#items td:first-child input').value,'混沌卷軸');
 assert.equal(d.querySelectorAll('#items tr').length,1);fill('#items td:nth-child(3) input',10000000);
 click('[data-preset="大師奇幻方塊"]');assert.equal(d.querySelectorAll('#items tr').length,2);
 assert.equal(d.querySelector('#items tr:first-child td:first-child input').value,'混沌卷軸');
 click('#items tr:last-child button');
 click('[data-preset="天氣"]');assert.equal(d.querySelector('#costs td:first-child input').value,'天氣');
 fill('#costs td:nth-child(2) input',2);fill('#costs td:nth-child(3) input',900);
 assert.equal(d.querySelector('#costs td:nth-child(4) input').value,'1000000');
 assert.equal(d.querySelector('#preview').textContent,'8,700,000 楓幣');
 submit('#lootForm');await until(()=>d.querySelector('.paid'),'settled');
 click('#assignPayout');assert.equal(d.querySelector('[name=user_id]').value,'1');
 fill('[name=user_id]','2');submit('#payoutOwnerForm');await until(closed,'payout owner assigned');
 await until(()=>w.testState.raids.find(r=>r.id===rosterRaid)?.payout_owner==='2','payout assignment reloaded');
 w.testRememberLogin('ui-transfer-token');click('#refresh');await until(()=>w.testState.me.id==='2','delegate signed in');
 assert.ok(d.querySelector('.paid'));assert.ok(d.querySelector('#resetLoot'));assert.ok(d.querySelector('#notify-payout'));
 assert.equal(d.querySelector('#assignPayout'),null);assert.equal(d.querySelector('.attend'),null);
 click('#notify-payout');await until(()=>d.querySelector('#notificationForm'),'payout notification loaded');
 assert.equal(d.querySelector('select[name=mode]'),null);
 assert.equal(d.querySelectorAll('textarea').length,1);
 assert.equal(d.querySelector('#notifyPreview').readOnly,false);
 assert.match(d.querySelector('#notifyPreview').value,/混沌卷軸/);
 assert.match(d.querySelector('#notifyPreview').value,/天氣/);
 assert.match(d.querySelector('#notifyPreview').value,/請聯繫 備選2 領取分寶/);
 assert.doesNotMatch(d.querySelector('#notifyPreview').value,/餘額/);
 assert.equal(d.querySelector('#submitNotify').disabled,false);
 assert.equal(d.querySelector('#submitNotify').textContent,'發送通知');
 click('#closeModal');
 w.testRememberLogin('ui-token');click('#refresh');await until(()=>w.testState.me.id==='1','leader restored');
 click('#assignPayout');fill('[name=user_id]','1');submit('#payoutOwnerForm');await until(closed,'payout owner reset to leader');
 await until(()=>!w.testState.raids.find(r=>r.id===rosterRaid)?.payout_owner,'default payout owner reloaded');
 assert.match(d.querySelector('.summary').textContent,/8,700,000/);
 click('.paid');await until(()=>d.querySelector('.paid')?.dataset.paid==='1','marked paid');
 click('#resetLoot');await until(()=>d.querySelector('#notice').textContent.includes('取消已領'),'paid reset prevented');
 click('#duplicate');fill('[name=title]','分隊原團');submit('#raidForm');
 await until(()=>d.querySelector('#detail h2')?.textContent==='分隊原團','split source created');
 const splitSource=w.testState.selected,splitSourceData=w.testState.raids.find(r=>r.id===splitSource);
 for(const user of ['2','3'])await db.prepare("INSERT INTO signups(raid_id,user_id,profile,note,available,seat,joined) VALUES(?,?,?,?,?,'waiting',?)").bind(splitSource,user,JSON.stringify({name:'分隊成員'+user,job:'主教',level:180,attack:50000,boss:0,ignore:0,dojo:user==='2'?'1.5E':'',deathSquad:user==='2'}),'保留備註','21:00',Date.now()).run();
 click('#refresh');await until(()=>d.querySelectorAll('.roster').length===3,'split candidates loaded');
 assert.equal(d.querySelector('.split-member'),null);
 click('#splitRaid');assert.equal(d.querySelector('#modalTitle').textContent,'新增分隊 · 選擇成員');
 assert.deepEqual([...d.querySelectorAll('.split-member-table th')].map(th=>th.textContent),['選擇','角色 / 職業','等級','乾表 / B傷 / 無視','武陵','敢死隊象徵']);
 assert.equal(d.querySelector('.split-member-table tbody tr').children[3].textContent,'50,000 / 0% / 0%');
 assert.equal(d.querySelector('.split-member-table tbody tr').children[4].textContent,'1.5E');
 assert.equal(d.querySelector('.split-member-table tbody tr').children[5].textContent,'有');
 assert.equal(d.querySelector('.split-member-table tbody tr:last-child').children[4].textContent,'—');
 assert.equal(d.querySelector('#splitNext').disabled,true);
 click('#selectSplit');assert.equal(d.querySelectorAll('.split-member:checked').length,2);
 submit('#splitMemberForm');assert.equal(d.querySelector('#modalTitle').textContent,'建立分隊');
 assert.equal(d.querySelector('[name=title]').value,'分隊原團 · 二隊');
 assert.equal(d.querySelector('[name=bosses]').value,splitSourceData.bosses.join(', '));
 assert.equal(d.querySelector('[name=location]').value,splitSourceData.location);
 assert.equal(d.querySelector('[name=requirements]').value,splitSourceData.requirements);
 assert.equal(d.querySelector('[name=note]').value,splitSourceData.note);
 assert.equal(d.querySelector('[name=starts]').value,new Date(Date.parse(splitSourceData.starts)+8*3600000).toISOString().slice(0,16));
 assert.deepEqual([...d.querySelector('[name=owner]').options].map(option=>option.value),['2','3']);
 click('#closeModal');assert.equal((await db.prepare('SELECT COUNT(*) AS n FROM signups WHERE raid_id=?').bind(splitSource).first()).n,3);
 click('#splitRaid');click('#selectSplit');submit('#splitMemberForm');fill('[name=owner]','3');fill('[name=title]','指定三號分隊');submit('#raidForm');
 await until(()=>d.querySelector('#detail h2')?.textContent==='指定三號分隊','split created and selected');
 const splitDestination=w.testState.selected;
 assert.equal((await db.prepare('SELECT owner FROM raids WHERE id=?').bind(splitDestination).first()).owner,'3');
 assert.equal((await db.prepare('SELECT COUNT(*) AS n FROM signups WHERE raid_id=?').bind(splitSource).first()).n,1);
 assert.equal((await db.prepare('SELECT COUNT(*) AS n FROM signups WHERE raid_id=?').bind(splitDestination).first()).n,2);
 assert.equal(d.querySelector('#saveRoster'),null);
 click('#logout');await until(()=>!d.querySelector('#welcome').hidden,'logged out');
 assert.doesNotMatch(d.cookie,/guild_token=/);
 console.log('PASS: UI sign-in, profile, create, attendance, settlement, linked cost conversion, payment lock, logout');
}finally{dom?.window.close();await mf.dispose()}
