const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const base=(window.API_BASE||'').replace(/\/$/,''), state={me:null,raids:[],selected:null,filter:'open',config:{}};
const fmt=v=>Number(v).toLocaleString('zh-TW'), when=v=>new Date(v).toLocaleString('zh-TW',{timeZone:'Asia/Taipei',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false});
const statuses={open:'招募中',running:'開打中',done:'已完成',cancelled:'已取消'};
const loginCookiePath=location.pathname.replace(/[^/]*$/,'');
function loginToken(){return document.cookie.split(';').map(s=>s.trim()).find(s=>s.startsWith('guild_token='))?.slice(12)||''}
function rememberLogin(token){document.cookie='guild_token='+encodeURIComponent(token)+'; Path='+loginCookiePath+'; Expires=Fri, 31 Dec 9999 23:59:59 GMT; SameSite=Lax'+(location.protocol==='https:'?'; Secure':'');sessionStorage.removeItem('guild_token')}
function forgetLogin(){document.cookie='guild_token=; Path='+loginCookiePath+'; Max-Age=0; SameSite=Lax';sessionStorage.removeItem('guild_token')}
const previousToken=sessionStorage.getItem('guild_token');if(previousToken&&!loginToken())rememberLogin(previousToken);else sessionStorage.removeItem('guild_token');
function notice(message){$('#notice').hidden=!message;$('#notice').textContent=message||''}
async function api(path,method='GET',data){const token=loginToken();const r=await fetch(base+'/api'+path,{method,headers:{...(data?{'Content-Type':'application/json'}:{}),...(token?{Authorization:'Bearer '+token}:{})},body:data?JSON.stringify(data):undefined});let result;try{result=await r.json()}catch{throw Error('無法讀取伺服器回應，請確認後端網址')}if(!r.ok){if(r.status===401){forgetLogin();state.me=null;renderAccount()}throw Error(typeof result.detail==='string'?result.detail:'欄位格式有誤，請檢查輸入')}return result}
async function action(fn){try{await fn()}catch(e){notice(e.message)}}
function modal(title,body){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=body;$('#modal').showModal()}
$('#closeModal').onclick=()=>$('#modal').close();
function formHandler(id,fn){$(id).onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('[type=submit]');button.disabled=true;try{await fn(new FormData(e.target));$('#modal').close();notice('');await load()}catch(e){let p=e.target.querySelector('.inline-error');if(!p){p=document.createElement('p');p.className='inline-error';p.setAttribute('role','alert');e.target.append(p)}p.textContent=e.message}finally{button.disabled=false}}}
function renderAccount(){$('#welcome').hidden=!!state.me;$('#workspace').hidden=!state.me;$('#newRaid').hidden=!state.me;$('#account').innerHTML=state.me?`<span>${esc(state.me.name)}</span><button id="logout">登出</button>`:'<span class="muted">Discord 帳號登入</span>';if(state.me)$('#logout').onclick=()=>action(async()=>{await api('/auth/logout','POST');forgetLogin();state.me=null;renderAccount()})}
async function load(){if(!loginToken()){state.me=null;state.raids=[];renderAccount();return}state.me=await api('/me');state.raids=await api('/raids');renderAccount();renderList();renderDetail()}
window.addEventListener('focus',()=>action(load));
const dateKey=v=>new Date(new Date(v).getTime()+8*3600000).toISOString().slice(0,10);
state.calendarDate=dateKey(Date.now());state.calendarMonth=state.calendarDate.slice(0,7);state.calendarRaid=null;
function selectDate(key){state.calendarDate=key;state.calendarMonth=key.slice(0,7);renderList()}
const raidTooltip=document.createElement('div');raidTooltip.id='raidTooltip';raidTooltip.role='tooltip';raidTooltip.hidden=true;document.body.append(raidTooltip);
function hideRaidTooltip(){raidTooltip.hidden=true}
function showRaidTooltip(button,r){
 if(!r)return;const count=r.members.filter(m=>m.seat==='confirmed').length,leader=r.members.find(m=>m.user_id===r.owner);
 raidTooltip.innerHTML=`<strong>${esc(r.title)}</strong><p>${esc(when(r.starts))} · ${statuses[r.status]}</p><p>${r.bosses.map(esc).join(' / ')}</p><dl><dt>人數</dt><dd>${count} / ${r.capacity} · 候補 ${r.members.length-count}</dd><dt>團長</dt><dd>${esc(leader?.profile.name||leader?.discord_name||'團長')}</dd><dt>地點</dt><dd>${esc(r.location)}</dd></dl>${r.requirements?`<p class="tooltip-note">要求：${esc(r.requirements)}</p>`:''}${r.note?`<p class="tooltip-note">備註：${esc(r.note)}</p>`:''}`;
 raidTooltip.hidden=false;const rect=button.getBoundingClientRect(),box=raidTooltip.getBoundingClientRect();
 raidTooltip.style.left=Math.max(8,Math.min(rect.left,window.innerWidth-box.width-8))+'px';
 raidTooltip.style.top=Math.max(8,rect.bottom+box.height+8<=window.innerHeight?rect.bottom+8:rect.top-box.height-8)+'px';
}
window.addEventListener('scroll',hideRaidTooltip,true);window.addEventListener('resize',hideRaidTooltip);document.addEventListener('keydown',e=>{if(e.key==='Escape')hideRaidTooltip()});
function renderList(){
 hideRaidTooltip();
 const calendarView=state.filter==='open';$('#calendar').hidden=!calendarView;
 document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter===state.filter));
 const selected=state.raids.find(r=>r.id===state.selected);
 if(selected&&state.calendarRaid!==selected.id){state.calendarRaid=selected.id;state.calendarDate=dateKey(selected.starts);state.calendarMonth=state.calendarDate.slice(0,7)}
 const raids=state.raids.filter(r=>state.filter==='all'||(state.filter==='open'?r.status==='open':r.members.some(m=>m.user_id===state.me.id))).sort((a,b)=>Date.parse(a.starts)-Date.parse(b.starts)||a.id-b.id);
 if(calendarView){
 const [year,month]=state.calendarMonth.split('-').map(Number),first=new Date(Date.UTC(year,month-1,1)),offset=(first.getUTCDay()+6)%7,today=dateKey(Date.now());
 const days=Array.from({length:42},(_,i)=>{const day=new Date(Date.UTC(year,month-1,i-offset+1)),key=day.toISOString().slice(0,10),events=raids.filter(r=>dateKey(r.starts)===key),weekend=i%7>=5;return `<div class="calendar-day ${key.slice(0,7)!==state.calendarMonth?'outside':''} ${weekend?'weekend':''} ${key===state.calendarDate?'selected-day':''}"><button class="calendar-date" data-date="${key}" aria-pressed="${key===state.calendarDate}" ${key===today?'aria-current="date"':''} aria-label="${key}，${events.length} 團"><span>${day.getUTCDate()}</span>${events.length?`<small>${events.length} 團</small>`:''}</button><div class="calendar-events">${events.slice(0,3).map(r=>`<button class="calendar-event ${r.status} ${r.id===state.selected?'selected-event':''}" data-raid="${r.id}" aria-describedby="raidTooltip" aria-label="${esc(when(r.starts)+' '+r.title)}"><time>${esc(new Date(r.starts).toLocaleTimeString('zh-TW',{timeZone:'Asia/Taipei',hour:'2-digit',minute:'2-digit',hour12:false}))}</time><span>${esc(r.title)}</span></button>`).join('')}${events.length>3?`<button class="calendar-more" data-date="${key}">＋${events.length-3} 團</button>`:''}</div></div>`});
 $('#calendar').innerHTML=`<div class="calendar-toolbar"><h2>${year} 年 ${month} 月</h2><div><button id="prevMonth" aria-label="上個月" title="上個月">‹</button><button id="calendarToday">今天</button><button id="nextMonth" aria-label="下個月" title="下個月">›</button></div></div><div class="calendar-weekdays">${['一','二','三','四','五','六','日'].map(d=>`<span>週${d}</span>`).join('')}</div><div class="calendar-grid">${days.join('')}</div>`;
 for(const [id,delta] of [['prevMonth',-1],['nextMonth',1]])$('#'+id).onclick=()=>selectDate(new Date(Date.UTC(year,month-1+delta,1)).toISOString().slice(0,10));
 $('#calendarToday').onclick=()=>selectDate(today);
 document.querySelectorAll('[data-date]').forEach(b=>b.onclick=()=>selectDate(b.dataset.date));
 }else $('#calendar').innerHTML='';
 const daily=calendarView?raids.filter(r=>dateKey(r.starts)===state.calendarDate):raids;
 $('#dayHeading').textContent=(calendarView?new Date(state.calendarDate+'T00:00:00+08:00').toLocaleDateString('zh-TW',{timeZone:'Asia/Taipei',month:'long',day:'numeric',weekday:'long'}):state.filter==='mine'?'我的團':'最近 100 團')+' · '+daily.length+' 團';
 $('#raidList').innerHTML=daily.length?daily.map(r=>{const n=r.members.filter(s=>s.seat==='confirmed').length;return `<button class="raid-card ${r.id===state.selected?'selected':''}" data-raid="${r.id}"><div class="card-head"><span class="eyebrow">${esc(when(r.starts))}</span><span class="badge ${r.status}">${statuses[r.status]}</span></div><h2>${esc(r.title)}</h2><p>${r.bosses.map(esc).join(' / ')}</p><div class="card-foot"><span>${esc(r.location)}</span><span>${n} / ${r.capacity} 人</span></div><div class="progress"><span style="width:${n/r.capacity*100}%"></span></div></button>`}).join(''):'<div class="empty">這一天沒有符合篩選的團隊。</div>';
 document.querySelectorAll('[data-raid]').forEach(b=>b.onclick=()=>{state.selected=Number(b.dataset.raid);state.calendarRaid=null;history.replaceState(null,'','#raid='+state.selected);renderList();renderDetail();$('#detail').focus({preventScroll:true});$('#detail').scrollIntoView?.({behavior:'smooth',block:'start'})});
 document.querySelectorAll('.calendar-event').forEach(b=>{const show=()=>showRaidTooltip(b,state.raids.find(r=>r.id===Number(b.dataset.raid)));b.onmouseenter=show;b.onfocus=show;b.onmouseleave=hideRaidTooltip;b.onblur=hideRaidTooltip});

}
$('#refresh').onclick=()=>action(async()=>{await load();notice('已更新最新報名名單')});
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;renderList()});
function renderDetail(){const r=state.raids.find(r=>r.id===state.selected);if(!r){$('#detail').innerHTML='<div class="empty">選擇一個團，查看隊伍與報名資訊。</div>';return}const owner=r.owner===state.me.id,mine=r.members.find(m=>m.user_id===state.me.id),n=r.members.filter(s=>s.seat==='confirmed').length;
$('#detail').innerHTML=`<div class="detail-top"><div><span class="eyebrow">RAID #${r.id}</span><h2>${esc(r.title)}</h2></div><span><span class="badge ${r.status}">${statuses[r.status]}</span></span></div><div class="tags">${r.bosses.map(b=>`<span class="tag">${esc(b)}</span>`).join('')}</div><dl class="info-grid"><div><dt>集合時間 · 台灣</dt><dd>${esc(when(r.starts))}</dd></div><div><dt>集合地點</dt><dd>${esc(r.location)}</dd></div><div><dt>正取 / 上限</dt><dd>${n} / ${r.capacity} · 候補 ${r.members.length-n}</dd></div><div><dt>團長</dt><dd>${esc(r.members.find(m=>m.user_id===r.owner)?.profile.name||'團長')}</dd></div></dl>${r.requirements?`<div class="note"><b>參加要求</b><br>${esc(r.requirements)}</div>`:''}${r.note?`<div class="note">${esc(r.note)}</div>`:''}<div class="actions">${r.status==='open'&&!mine?'<button class="primary" id="join">報名這團</button>':''}${r.status==='open'&&mine&&!owner?'<button id="leave">退出報名</button>':''}${owner&&r.status==='open'?'<button id="edit">修改團隊</button><button id="start" class="primary">開始打王</button><button id="cancel" class="danger">取消團隊</button>':''}${owner&&r.status==='running'?'<button id="done" class="primary">完成打王</button>':''}${owner&&state.config.discord_ready?'<button id="sync">同步至 Discord</button>':''}<button id="share">複製招募文字</button></div>${r.sync_error?`<p class="danger">${esc(r.sync_error)}</p>`:''}<h3>報名名單</h3><div class="table-wrap"><table><thead><tr><th>角色 / 職業</th><th>等級 / 乾表</th><th>B 傷 / 無視</th><th>狀態</th><th>可參加時段 / 備註</th>${['running','done'].includes(r.status)?'<th>出席</th>':''}</tr></thead><tbody>${r.members.map(m=>`<tr><td><strong>${esc(m.profile.name)}</strong><small>${esc(m.profile.job)}</small></td><td>${m.profile.level}<small>${fmt(m.profile.attack)}</small></td><td>${m.profile.boss}%<small>${m.profile.ignore}%</small></td><td>${m.seat==='waiting'?'候補':'正取'}${m.user_id===r.owner?'<small>團長</small>':''}</td><td>${esc(m.available||'依團隊時間')}<small>${esc(m.note)}</small></td>${['running','done'].includes(r.status)?`<td>${owner&&!r.settlement&&m.seat==='confirmed'?`<input class="attend" type="checkbox" aria-label="${esc(m.profile.name)}出席" data-user="${esc(m.user_id)}" ${m.attended?'checked':''}>`:m.attended?'已出席':'—'}</td>`:''}</tr>`).join('')}</tbody></table></div>${owner&&['running','done'].includes(r.status)&&!r.settlement?'<div class="actions"><button id="saveAttendance">儲存出席名單</button><span class="muted">勾選實際出席者後儲存，再進行分寶。</span></div>':''}${r.status==='done'?lootView(r,owner):''}`;
const bind=(id,fn)=>{const b=$('#'+id);if(b)b.onclick=()=>action(fn)};
bind('join',()=>joinForm(r));bind('leave',async()=>{if(confirm('確定退出這團？候補將自動遞補。')){await api(`/raids/${r.id}/join`,'DELETE');await load()}});bind('edit',()=>raidForm(r));
for(const [id,value,label] of [['start','running','開始打王並停止報名'],['done','done','完成打王'],['cancel','cancelled','取消這個團']])bind(id,async()=>{if(confirm(`確定${label}？`)){await api(`/raids/${r.id}/status`,'PUT',{status:value});await load()}});
bind('sync',async()=>{await api(`/raids/${r.id}/discord`,'POST');await load();notice('Discord 招募訊息已更新。成員可點連結回網站報名。')});bind('share',()=>share(r));bind('saveAttendance',async()=>{await api(`/raids/${r.id}/attendance`,'PUT',{users:[...document.querySelectorAll('.attend:checked')].map(e=>e.dataset.user)});await load();notice('出席名單已儲存')});bind('loot',()=>lootForm(r));bind('resetLoot',async()=>{if(confirm('確定清除結算並重新計算？')){await api(`/raids/${r.id}/settlement`,'DELETE');await load()}});
document.querySelectorAll('.paid').forEach(b=>b.onclick=()=>action(async()=>{await api(`/raids/${r.id}/paid/${encodeURIComponent(b.dataset.user)}`,'PUT',{paid:b.dataset.paid!=='1'});await load()}));const duplicate=document.createElement('button');duplicate.id='duplicate';duplicate.textContent='複製並開團';duplicate.onclick=()=>raidForm(r,true);$('#detail .actions').append(duplicate);}
function profileForm(id=state.me.characters?.[0]?.id){const p=state.me.characters?.find(c=>c.id===id)?.profile||{};modal('我的角色',`${characterPicker(id,true)}<form id="profileForm"><p class="muted">乾表填完整數字，例如 3.7 萬填 37000。資料更新會用於下一次報名。</p><label>角色 ID<input name="name" required maxlength="32" value="${esc(p.name)}"></label><label>職業<input name="job" required maxlength="24" placeholder="例如：聖騎士" value="${esc(p.job)}"></label><div class="form-grid"><label>等級<input name="level" type="number" min="1" max="300" required value="${p.level||140}"></label><label>乾表<input name="attack" type="number" min="0" max="1000000000" required value="${p.attack||0}"></label><label>B 傷 (%)<input name="boss" type="number" min="0" max="5000" step="0.1" required value="${p.boss||0}"></label><label>無視 (%)<input name="ignore" type="number" min="0" max="100" step="0.1" required value="${p.ignore||0}"></label></div><button class="primary" type="submit">儲存角色</button></form>`);formHandler('#profileForm',async f=>{await api(id?'/me/characters/'+encodeURIComponent(id):'/me/characters',id?'PUT':'POST',{name:f.get('name'),job:f.get('job'),...Object.fromEntries(['level','attack','boss','ignore'].map(k=>[k,Number(f.get(k))]))})});$('#manageCharacter').onchange=e=>profileForm(e.target.value);$('#addCharacter').onclick=()=>profileForm('')}
$('#profileButton').onclick=()=>profileForm();
function characterPicker(id,manage=false){return `<label>遊戲角色<select ${manage?'id="manageCharacter"':'name="character_id" required'}>${manage&&!id?'<option value="">新增角色</option>':''}${(state.me.characters||[]).map(c=>`<option value="${esc(c.id)}" ${c.id===id?'selected':''}>${esc(c.profile.name)} / ${esc(c.profile.job)} / Lv.${c.profile.level}</option>`).join('')}</select></label>${manage?'<button type="button" id="addCharacter">＋ 新增角色</button>':''}`}
$('#historyButton').onclick=()=>action(async()=>{const rows=await api('/me/history');modal('參團紀錄',`<div class="table-wrap"><table><thead><tr><th>團隊 / 時間</th><th>角色</th><th>出席 / 分寶</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.title)}<small>${esc(when(r.starts))} · ${statuses[r.status]}</small></td><td>${esc(r.profile.name)}<small>${esc(r.profile.job)} · Lv.${r.profile.level}</small></td><td>${r.attended?'已出席':r.seat==='waiting'?'候補':'未出席'}<small>${r.settlement?.result.users.includes(state.me.id)?fmt(r.settlement.result.each)+' 楓幣 · '+(r.paid?'已領取':'未領取'):'未分寶'}</small></td></tr>`).join('')||'<tr><td colspan="3">尚無參團紀錄</td></tr>'}</tbody></table></div>`)});

function localDate(s){const d=new Date(s);return new Date(d.getTime()+8*3600000).toISOString().slice(0,16)}
function raidForm(r,copy=false){const editing=!!r&&!copy;if(!state.me.characters?.length){profileForm();return}modal(editing?'修改團隊':copy?'複製並開團':'自由開團',`<form id="raidForm">${editing?'':characterPicker()}<label>團隊名稱<input name="title" maxlength="80" required placeholder="例如：週六晚間王團" value="${esc(r?.title)}"></label><label>打王項目（以逗號分隔）<input name="bosses" required placeholder="炎魔, 闇黑龍王, 皮卡啾" value="${esc(r?.bosses.join(', '))}"></label><div class="form-grid"><label>集合時間 · 台灣<input name="starts" type="datetime-local" required value="${editing?localDate(r.starts):localDate(new Date(Date.now()+3600000))}"></label><label>人數上限（含團長）<input name="capacity" type="number" min="1" max="60" required value="${r?.capacity||6}"></label></div><label>集合地點<input name="location" maxlength="100" value="${esc(r?.location||'當天公告')}"></label><label>參加要求<textarea name="requirements" maxlength="1000" placeholder="等級、乾表、所需職業；由團長確認">${esc(r?.requirements)}</textarea></label><label>團隊備註<textarea name="note" maxlength="1000" placeholder="例如：時間可能調整，不打某個王請在報名備註填寫">${esc(r?.note)}</textarea></label><button class="primary" type="submit">${editing?'儲存修改':'建立團隊並加入'}</button></form>`);formHandler('#raidForm',async f=>{const data={character_id:f.get('character_id'),title:f.get('title'),bosses:f.get('bosses').split(/[,，]/).map(s=>s.trim()).filter(Boolean),starts:new Date(f.get('starts')+':00+08:00').toISOString(),capacity:Number(f.get('capacity')),location:f.get('location'),requirements:f.get('requirements'),note:f.get('note')};const result=await api(editing?`/raids/${r.id}`:'/raids',editing?'PUT':'POST',data);state.selected=editing?r.id:result.id;state.filter='all';history.replaceState(null,'','#raid='+state.selected)})}
$('#newRaid').onclick=()=>raidForm();
function joinForm(r){if(!state.me.characters?.length){profileForm();return}modal('報名 · '+r.title,`<form id="joinForm">${characterPicker()}<label>可參加時段<input name="available" maxlength="100" placeholder="例如：21:30–23:30；留空表示依團隊時間"></label><label>報名備註<textarea name="note" maxlength="500" placeholder="不打的王、提早或晚到需求"></textarea></label><p class="muted">額滿後自動進候補；正取退出後依報名順序遞補。每個 Discord 帳號在一團只報名一次。</p><button class="primary" type="submit">確認報名</button></form>`);formHandler('#joinForm',async f=>await api(`/raids/${r.id}/join`,'POST',{character_id:f.get('character_id'),note:f.get('note'),available:f.get('available')}))}
function share(r){const text=`【${r.title}】\n項目：${r.bosses.join(' / ')}\n集合：${when(r.starts)}（台灣）\n地點：${r.location}\n人數：${r.members.filter(m=>m.seat==='confirmed').length}/${r.capacity}\n要求：${r.requirements||'無'}\n備註：${r.note||'無'}\n報名連結：${location.href.split('#')[0]}#raid=${r.id}`;modal('招募文字',`<textarea class="share-text" readonly aria-label="招募文字">${esc(text)}</textarea><button id="copy" class="primary">複製</button>`);$('#copy').onclick=()=>action(async()=>{await navigator.clipboard.writeText(text);$('#copy').textContent='已複製'})}
function lootView(r,owner){if(!r.settlement)return `<section class="loot"><h2>戰利品分寶</h2><p>依本團實際出席名單，扣除手續費與成本後均分。</p>${owner?'<button id="loot" class="primary">記錄掉寶並結算</button>':'<p class="muted">等待團長確認出席與結算。</p>'}</section>`;const s=r.settlement.result;return `<section class="loot"><h2>本團分寶</h2><div class="summary">每位出席者可分得<strong>${fmt(s.each)} 楓幣</strong><small>${s.count} 人均分 · 餘額 ${fmt(s.remainder)} 楓幣由團長保留，另行分配</small></div><div class="info-grid"><div>總售價<p>${fmt(s.gross)}</p></div><div>手續費<p>${fmt(s.fee)}</p></div><div>成本<p>${fmt(s.cost)}</p></div><div>淨收益<p>${fmt(s.total)}</p></div></div><div class="table-wrap"><table><thead><tr><th>角色</th><th>可領楓幣</th><th>領取狀態</th></tr></thead><tbody>${r.members.filter(m=>s.users.includes(m.user_id)).map(m=>`<tr><td>${esc(m.profile.name)}</td><td>${fmt(s.each)}</td><td>${owner?`<button class="paid" data-user="${esc(m.user_id)}" data-paid="${m.paid}">${m.paid?'已領取 ✓':'標記已領'}</button>`:m.paid?'已領取':'未領取'}</td></tr>`).join('')}</tbody></table></div>${owner?'<div class="actions"><button id="resetLoot">清除結算 / 重新計算</button></div>':''}</section>`}
function lootForm(r){const count=r.members.filter(m=>m.attended).length;if(!count)throw Error('請先儲存實際出席名單');modal('戰利品分潤 · '+count+' 人',`<form id="lootForm"><div class="form-grid"><label>拍賣場手續費 (%)<input id="fee" type="number" min="0" max="100" step="0.1" value="3" required></label><label>1 千萬楓幣 = 多少楓點<input id="rate" type="number" min="1" value="9000" required></label></div><h3>戰利品收益</h3><div class="table-wrap"><table class="loot-editor" aria-label="戰利品收益"><colgroup><col class="name-column"><col class="quantity-column"><col class="amount-column"><col class="remove-column"></colgroup><thead><tr><th scope="col">物品名稱</th><th scope="col">數量</th><th scope="col">單價（楓幣）</th><th scope="col">刪除</th></tr></thead><tbody id="items"></tbody></table></div><button id="addItem" type="button">＋ 新增物品</button><h3>成本扣除</h3><div class="table-wrap"><table class="loot-editor cost-editor" aria-label="成本扣除"><colgroup><col class="name-column"><col class="quantity-column"><col class="amount-column"><col class="amount-column"><col class="remove-column"></colgroup><thead><tr><th scope="col">成本名稱</th><th scope="col">數量</th><th scope="col">總楓點</th><th scope="col">總楓幣</th><th scope="col">刪除</th></tr></thead><tbody id="costs"></tbody></table></div><p class="muted">金額填該筆成本總額。</p><button id="addCost" type="button">＋ 新增成本</button><div class="summary">每人預估可分得<strong id="preview">0 楓幣</strong><small>向下取整數，差額保留為本團餘額。</small></div><button class="primary" type="submit">儲存結算</button></form>`);
const row=(cost=false)=>{const div=document.createElement('tr');div.dataset.basis='points';div.className='loot-row';div.innerHTML=cost?'<input aria-label="成本名稱" placeholder="例如：白金神奇剪刀" required maxlength="80"><input aria-label="成本數量" type="number" min="1" max="100000" value="1" required><input aria-label="成本總楓點" type="number" min="0" max="1000000000000" value="0" required><input aria-label="成本總楓幣" type="number" min="0" max="1000000000000" value="0" required><button type="button" aria-label="刪除成本">✕</button>':'<input aria-label="物品名稱" placeholder="例如：混沌卷軸" required maxlength="80"><input aria-label="物品數量" type="number" min="1" max="100000" value="1" required><input aria-label="物品單價" type="number" min="0" max="1000000000000" value="0" required><button type="button" aria-label="刪除物品">✕</button>';for(const input of [...div.children]){const cell=document.createElement('td');cell.append(input);div.append(cell)}$(cost?'#costs':'#items').append(div);div.querySelector('button').onclick=()=>{div.remove();preview()};if(cost){const inputs=div.querySelectorAll('input');inputs[2].oninput=()=>{div.dataset.basis='points';inputs[3].value=Math.floor(Number(inputs[2].value)*10000000/Number($('#rate').value))};inputs[3].oninput=()=>{div.dataset.basis='mesos';inputs[2].value=Math.floor(Number(inputs[3].value)*Number($('#rate').value)/10000000)}}};
const payload=()=>({fee:Number($('#fee').value),rate:Number($('#rate').value),items:[...$('#items').children].map(d=>{const a=[...d.querySelectorAll('input')].map(i=>i.value);return {name:a[0],quantity:Number(a[1]),price:Number(a[2])}}),costs:[...$('#costs').children].map(d=>{const a=[...d.querySelectorAll('input')].map(i=>i.value);return {name:a[0],quantity:Number(a[1]),points:Number(a[2]),mesos:Number(a[3]),basis:d.dataset.basis}})});
function preview(){const p=payload();const gross=p.items.reduce((a,i)=>a+i.quantity*i.price,0),cost=p.costs.reduce((a,c)=>a+(c.basis==='mesos'?c.mesos:c.points*10000000/p.rate),0);$('#preview').textContent=fmt(Math.floor((gross*(1-p.fee/100)-cost)/count))+' 楓幣'}
$('#rate').oninput=()=>{document.querySelectorAll('#costs .loot-row').forEach(d=>{const a=d.querySelectorAll('input');if(d.dataset.basis==='points')a[3].value=Math.floor(Number(a[2].value)*10000000/Number($('#rate').value));else a[2].value=Math.floor(Number(a[3].value)*Number($('#rate').value)/10000000)})};row();$('#addItem').onclick=()=>row();$('#addCost').onclick=()=>row(true);$('#lootForm').oninput=preview;formHandler('#lootForm',async()=>await api(`/raids/${r.id}/settlement`,'POST',payload()));}
$('#login').onclick=()=>action(async()=>{if(state.selected)sessionStorage.setItem('pending_raid',String(state.selected));const verifier=Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,'0')).join('');sessionStorage.setItem('login_verifier',verifier);const challenge=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier))),b=>b.toString(16).padStart(2,'0')).join('');location.href=base+'/api/auth/login?challenge='+challenge+'&return_to='+encodeURIComponent(location.origin+location.pathname)});$('#demo').onclick=()=>action(async()=>{const r=await api('/auth/demo','POST');rememberLogin(r.token);await load()});
(async()=>{try{state.config=await api('/config');$('#demo').hidden=!state.config.demo;$('#setup').textContent=state.config.login_ready?'任何 Discord 帳號皆可登入，不限伺服器成員。':'站長尚未設定 Discord 登入；設定完成後即可使用。';$('#login').disabled=!state.config.login_ready;const hash=new URLSearchParams(location.hash.slice(1));if(hash.has('ticket')){const ticket=hash.get('ticket');history.replaceState(null,'',location.pathname+location.search);const verifier=sessionStorage.getItem('login_verifier')||'';const r=await api('/auth/exchange','POST',{ticket,verifier});sessionStorage.removeItem('login_verifier');rememberLogin(r.token)}if(hash.has('raid'))state.selected=Number(hash.get('raid'));else if(sessionStorage.getItem('pending_raid')){state.selected=Number(sessionStorage.getItem('pending_raid'));sessionStorage.removeItem('pending_raid');history.replaceState(null,'','#raid='+state.selected)}await load()}catch(e){renderAccount();notice(e.message)}})();
